---

- name: install dependencies
  become: true
  apt:
    name:
      - python3-pip
      - python3-dev
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-setuptools

- name: create project directory
  file:
    path: /home/pi/dobot
    state: directory
    mode: '0755'
    owner: pi
    group: pi

- name: install pip packages
  become: true
  pip:
    name:
      - wheel
      - pyserial
      - flask
      - gunicorn
      - gpiozero
      - RPi.GPIO

